### PR TITLE
enforce an tsc check before running test, fix front-end test; and provide a way to mock useContext

### LINKED ISSUE #121: Fix frontend unit test, which is actually not working now.

### PR DESCRIPTION
**Pull request by sherlockq**
Resolves #121 
### ways to mock useContext
the trick is to move useContext of react into our own module, and call that instead to make it mockable.

```
import * as SessionsContext from "./sessionsContext";
...
const sessions: SessionsContext.ISession[] = [
    {
      id: 0,
      title: "title",
      location: "location",
      time: "12:00",
      presenter: "presenter"
    }
  ];

  jest
    .spyOn(SessionsContext, "useSessionsContext")
    .mockImplementation(() => ({
    sessions: sessions,
    setSessions: jest.fn(),
    currentSession: undefined,
    setCurrentSession: jest.fn()
  }));

```

### CODE REVIEW

File: packages/frontend/app/src/session/Sessions.tsx [hunk 1]
```diff
@@ -1,14 +1,18 @@
...
+} from "./sessionsContext";
 import * as sessionStorage from "../common/sessionsLocalStorage";
 
 interface SessionsProps {
   isFilteringByInterest: boolean;
 }
 
 const Sessions: React.FC<SessionsProps> = props => {
-  const { sessions } = useContext(SessionsContext);
+  // const { sessions } = useContext(SessionsContext);
```
Comment (jmir17) [inline packages/frontend/app/src/session/Sessions.tsx]: We have git!!!

Comment (sherlockq) [reply packages/frontend/app/src/session/Sessions.tsx]: Thanks! Removed!
